import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { TRPCReactProvider } from "@/trpc/client";
import MultiModalProvider from "@/components/modals/multi-modals/multi-modals/multi-modal-provider";
import AuthModalProvider from "@/components/modals/auth-modal/auth-modal-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased
        h-screen`}
      >
        <Toaster />
        <TRPCReactProvider>
          <AuthModalProvider />
          <MultiModalProvider />
          {children}
        </TRPCReactProvider>
      </body>
    </html>
  );
}
